import Head from "next/head";
import Link from "next/link";
import Header from "../../components/Header";
import { DivWrapper } from "@/src/components/DivWrapper/styles";
import Button from "@/src/components/Button";
import { HomeContainer } from "./styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Header />

      <HomeContainer>
        <DivWrapper>
          <h1>Lorem ipsum dolor sit amet</h1>

          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestiae
            iusto voluptatem obcaecati omnis error architecto neque cum
            exercitationem fugiat. Vero illo autem eum nisi sapiente, odio optio
            accusamus cupiditate ad.
          </p>
          <Link href="/products">
            <Button>See more</Button>
          </Link>
        </DivWrapper>
      </HomeContainer>
    </>
  );
}
