import type { AppProps } from "next/app";

import Head from "next/head";
import { CartContextProvider } from "../hooks/useCart";
import { Inter } from "next/font/google";
import { GlobalStyle } from "../styles/global";
import { ThemeProvider } from "styled-components";
import { defaultTheme } from "../styles/themes/default";

const inter = Inter({ subsets: ["latin"] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className={inter.className}>
      <ThemeProvider theme={defaultTheme}>
        <CartContextProvider>
          <GlobalStyle />
          <Head>
            <title>Next E-Commerce</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
          </Head>

          <Component {...pageProps} />
        </CartContextProvider>
      </ThemeProvider>
    </div>
  );
}
